### ISSUE TITLE
setSimulationPath() leapyear handling seems bugged

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresRead#112]
If I load a study with the following parameters : 
```
horizon = 2020
january.1st = Wednesday
leapyear = true
```

I have the following warning and automatic correction of the parameters : 
```
Warning message:
Parameter 'horizon' is missing or inconsistent with 'january.1st' and 'leapyear'. Assume correct year is 2017.
To avoid this warning message in future simulations, open the study with Antares and go to the simulation tab, put a valid year number in the cell 'horizon' and use consistent values for parameters 'Leap year' and '1st january'.
```

While 2020 starts a Wednesday and is a leap year.

**Comment by jalazawa** [comment]
What is the first month of the year in your study? 

If the first month is July-2020 then Feb-2021 has 28 days. 
If the first month is Jan-2020 then Feb-2020 has 29 days. 

I added some tests [here](https://github.com/rte-antares-rpackage/antaresRead/blob/3597564cd4348a6a9fa8c0002bab82de5262060f/tests/testthat/test-getStartDate.R#L62) and I think there is no bug with leap year. 

Mastering system date of ANTARES will take some time.

**Comment by jalazawa** [comment]
Close with #121

**Comment by jalazawa** [comment]
Done.
