### ISSUE TITLE
Get the value of the maximum flow capacity for the link of the study

### ISSUE THREAD

**Issue by Maxxouxx** [rte-antares-rpackage/antaresRead#113]
Hello,

Using antaresRead, is it possible to get the value of maximum flow capacity for the different links of a study? (using linkCapacity?)

Thank you in advance!

Maxime

**Comment by jalazawa** [comment]
Yes, I added an example [here](http://htmlpreview.github.io/?https://github.com/rte-antares-rpackage/antaresME/blob/master/antaresReadME.html). 

In the future, I will add more examples not directly attached to a readAntares function but related to data.table or general use of R.

**Comment by Maxxouxx** [comment]
Thanks :)
