### ISSUE TITLE
Type of variable from <- readAntares

### ISSUE THREAD

**Issue by Maxxouxx** [rte-antares-rpackage/antaresRead#114]
Hello,

I would like to know what type of variable is created when using readAntares? (typeof() returns list, but it is not very precise).

I would like to know that because I'm very interested by the possibility of easy selection as for example:
`all_hours_all_MC <-readAntares(areas = all_areas, mcYears ="all", showProgress = TRUE)
pb_hours <- all_hours_all_MC["UNSP. ENRG">0]`

In fact, I would like to create the same type of object (from excel table) to be able to proceed as easily for future selections.

Thank you in advance for your answer.

Maxime

**Comment by Maxxouxx** [comment]
I think I just find it ... Is it a type data.table ?

**Comment by jalazawa** [comment]
You can use this 

```R
> class(all_hours_all_MC )
[1] "antaresDataTable" "antaresData"     
[3] "data.table"       "data.frame" 

```

It's an antaresDataTable, an antaresData, an data.table and a data.frame. 

I will add more info about this.

**Comment by jalazawa** [comment]
@Maxxouxx , you can find more information [here ](https://htmlpreview.github.io/?https://github.com/rte-antares-rpackage/antaresME/blob/master/antaresReadME.html#how-can-i-know-the-type-and-class-of-my-object) about your question

**Comment by Maxxouxx** [comment]
Thank you :)
