### ISSUE TITLE
Problem with  setSimulationPath()

### ISSUE THREAD

**Issue by martapon** [rte-antares-rpackage/antaresRead#118]
Hello, First of all, thank you very much for moving ANTARES to an open source software. I am trying to learn how to use if but when I try to specify a setSimulationPath it always give me the same error: "Error in .getPaths(path, simulation) : Directory is not an Antares study." 
Could you please give more info about the problem? 
Thank you very much in advance,
Marta

**Comment by jalazawa** [comment]
Hey, 

Could you code this? 


```R
studyPath <- "path/to/study"
setSimulationPath(path = studyPath, simulation = -1)
myData<-readAntares(areas = "all", links = "all")

```
studyPath must be a path to a folder containing an antares project, so containing a file `study.antares`.

if this is not working, try 

```R
studyPath <- "D:\\path\\to\\study"

#or 

studyPath <- "D:/path/to/study"

#or 

studyPath <- "D://path//to//study"
```

**Comment by jalazawa** [comment]
@martapon have you found a solution to your problem? Can we close this issue?

**Comment by martapon** [comment]
Yes, thanks,
Marta
