### ISSUE TITLE
Issue when analyzing simulations when starting month > July

### ISSUE THREAD

**Issue by janusdebondt** [rte-antares-rpackage/antaresRead#121]
It seems the month August was forgotten from the line below.

https://github.com/rte-antares-rpackage/antaresRead/blob/4534dd7e42ab919dfb8827b3e1032e91b0926818/R/setSimulationPath.R#L430

**Comment by jalazawa** [comment]
Thanks, I will add some automatic tests to `.getStartDate()` in the next version.

**Comment by jalazawa** [comment]
Done with [this](https://github.com/rte-antares-rpackage/antaresRead/commit/02dd4fd32752fb085bf96eb6c8a74adefebae6b3)
