### ISSUE TITLE
readInputTS seems to neglect simOptions$timeMaxId when selecting timeStep = "annual"

### ISSUE THREAD

**Issue by jorritvm** [rte-antares-rpackage/antaresRead#122]
Hi, 
Not sure if this is intended behaviour but there seems to be an inconsistency in what subset of data is read when you select a different timeStep.

E.g. I have a simulation with 4386 hours (oktober -> end of march).
I take simOptions from this simulation, modify the starting date (due to the bug reported by Janus) and modify the timeMaxId to 8760 because we have a 'feeling' for annual numbers, and not so much for winter data.

When I load hourly data and sum the columns the values are different from loading the data using timeStep = "annual". The second method seems to neglect timeMaxId.

```
> newOptions$timeIdMin
[1] 1
> newOptions$timeIdMax
[1] 8760
> dtror = readInputTS(ror = areas, opts = newOptions, timeStep = "hourly")
> dtror = dtror[, .(yearly_ror_production = sum(ror, na.rm = TRUE)), by = .(area,tsId)]
> print(dtror)
'antaresDataTable' object with dimension 210 x 3
     area tsId yearly_ror_production
  1:   be    1                291600 # this is a TRUE annual value
  2:   be    2                501168
  3:   be    3                221328
  4:   be    4                262872
  5:   be    5                303168

as opposed to ... 

> dtror = readInputTS(ror = areas, opts = newOptions, timeStep = "annual")
> print(dtror)
'antaresDataTable' object with dimension 210 x 5
     area timeId time tsId    ror
  1:   be      1 2018    1 186528 # this is only a PARTLY value
  2:   be      1 2018    2 309168
  3:   be      1 2018    3 132984
  4:   be      1 2018    4 150144
  5:   be      1 2018    5 159384
```

**Comment by jalazawa** [comment]
This issue is linked to #121

**Comment by jalazawa** [comment]
You can find the correction and a new test [here](https://github.com/rte-antares-rpackage/antaresRead/commit/254f3d8f172e28d0380cc03b57bf4b131bf1018b), I will close this issue when I will resolve #121 

Thanks for your example, it helped me a lot. 

If you want to test, you can install this branch with 

```R
devtools::install_github("rte-antares-rpackage/antaresRead", ref ="pat
ch_v221")
```

**Comment by jalazawa** [comment]
DONE.
