### ISSUE TITLE
readInputTS reads timeseries that are not activated in antares

### ISSUE THREAD

**Issue by jorritvm** [rte-antares-rpackage/antaresRead#124]
Sometimes when quickly comparing sensitivities of a model we would copy paste a set of thermal series.
This is the case for example for FR NUC. However, in clusters, only one set will be defined at one time, therefor, only 1 set is "activated" in antares at once.

In readInputTS() however, all TS seem to be read, and not just the ones that are configured in antares (input/thermal/clusters/fr/lists.ini).

Example:
> x = readInputTS(thermalAvailabilities = "fr")
> y = x[cluster %like% "nuk"]
> y[,unique(cluster)]
 [1] "fr_nuke_1310"              "fr_nuke_1310_2018"         "fr_nuke_1310_2019"         "fr_nuke_1500"             
 [5] "fr_nuke_1500_2018"         "fr_nuke_1500_2019"         "fr_nuke_910"               "fr_nuke_910_2018"         
 [9] "fr_nuke_910_2019"          "fr_nuke_flamanville3"      "fr_nuke_flamanville3_2019"

In the above model, only the _2019 suffixed ones are actually used. 
Do you think it would be possible to modify readInputTS to look in the list.ini file and read only the TS of the clusters activated there?

**Comment by jalazawa** [comment]
Actually, readInputTS() get the list of clusters by exploring the folder in "thermal/series/fr", to take the activated clusters we must read the file "thermal/clusters/fr/lists.ini" and maybe take into account the option "enabled". 

The line to edit is [here](https://github.com/rte-antares-rpackage/antaresRead/blob/master/R/importInput.R#L94). 

Thanks for your example. @jorritvm 

In your example, you could have done that to reduce memory usage and increase the speed 
(i and j of data.table in the same line) 
```R
x <- readInputTS(thermalAvailabilities = "fr")
x[ cluster %like% "nuc", unique(cluster)]

```

**Comment by jorritvm** [comment]
Jalal, thanks for treating this. Also big thanks for your tip on data.table i & j conciseness. I always welcome feedback from a more experienced coder ! ;-)
