### ISSUE TITLE
removeVirtualAreas bugs with districts

### ISSUE THREAD

**Issue by janusdebondt** [rte-antares-rpackage/antaresRead#127]
When calling `removeVirtualAreas` if districts are present, the following error is produced: 

![image](https://user-images.githubusercontent.com/2463651/51622835-bf05c700-1f37-11e9-8654-320c2d0872b5.png)

https://github.com/rte-antares-rpackage/antaresRead/blob/b0e9fe822748ca6c69ade433c8a53900e2512e9f/R/removeVirtualAreas.R#L467

The error is caused in `rbindlist`, but can be avoided if the "all areas" district is removed from the district list (\input\areas\sets.ini). A small example to generate the error can be supplied if it is not clear. 

Possibly the line below shouldn't include the "all areas" district?

https://github.com/rte-antares-rpackage/antaresRead/blob/b0e9fe822748ca6c69ade433c8a53900e2512e9f/R/groupByDistrict.R#L29

**Comment by etienne-s** [comment]
Hi Janus,

Thanks for your report. Unfortunately I cannot reproduce this error. Maybe it has been fixed by a previous commit.

Can you still reproduce it? And if so, could you provide a small example?

Thanks,
Etienne

**Comment by janusdebondt** [comment]
Hi Etienne,

Indeed, the example can still be reproduced. Please find a minimal example with R script below.

Kind regards,
Janus

[Remove Virtual Areas.zip](https://github.com/rte-antares-rpackage/antaresRead/files/3895860/Remove.Virtual.Areas.zip)

**Comment by etienne-s** [comment]
Hi!

Thanks a lot for your reproducible example. We've just pushed a fix that should solve this problem.

Please let us know if you still encounter issues with that function.

**Comment by janusdebondt** [comment]
Hi Etienne,

I have performed a github-install of the master branch just now, and retried with the provided example. However, I am still getting an error (see screenshot below).

![image](https://user-images.githubusercontent.com/2463651/70066024-48703600-15ec-11ea-87fc-cd3d186b08db.png)

**Comment by etienne-s** [comment]
Strange, I've just tested it again and it works fine for me. Could you tell me which version of data.table you're using?

**Comment by janusdebondt** [comment]
Hi Etienne,

It seems indeed that a data.table update solved the remaining issue. The example now works fine. Thanks a lot for your help!

Kind regards,
Janus
