### ISSUE TITLE
the website for bpnumerique is no more available

### ISSUE THREAD

**Issue by cderv** [rte-antares-rpackage/antaresRead#130]
the website is mentioned in [DESCRIPTION](https://github.com/rte-antares-rpackage/antaresRead/blob/aecc78210885686e9b82e0049009f3722d44c85a/DESCRIPTION#L17)
`You can see the results of several ANTARES studies here : <http://bpnumerique.rte-france.com/>. `

However, it is no more available.

**Comment by etienne-s** [comment]
Thanks Christophe. Do you know any equivalent resources? I could not find anything so I just removed the link.

**Comment by cderv** [comment]
No the website was unpublished with no new one I think.
