### ISSUE TITLE
select parameter doesn't work when importing clusters

### ISSUE THREAD

**Issue by janusdebondt** [rte-antares-rpackage/antaresRead#142]
As the select parameter is ignored when importing cluster data, I believe it could be good to mention this in the documentation as well.

https://github.com/rte-antares-rpackage/antaresRead/blob/d62ce0684e41589d292a077022d3adc2695cf3c0/R/readAntares.R#L417

**Comment by etienne-s** [comment]
Thanks for this remark. Do you think it would be useful if this parameter was taken into account for cluster data? Or is it sufficient to just add a mention in the documentation?

**Comment by janusdebondt** [comment]
I encountered this while trying to optimise data reading, so to speed this up. As I have not been able to test the gains this could have it is difficult to assess. Could be useful, but not a must-have I would say.

**Comment by etienne-s** [comment]
Thanks, it seems that if we changed the behaviour we'd be more likely to break existing code than to really help anybody, so we're going to leave it like that for now. We'll just add a note in the docs.
