### ISSUE TITLE
parAggregateMCall en parallèle

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [rte-antares-rpackage/antaresRead#161]
Bonjour à vous,

En travaillant avec l'adequacy patch, j'ai eu l'occasion d'utiliser la fonction parAggregateMCall d'antaresRead. Il s'avère que lorsqu'on utilise parAggregateMCall en parallèle à l'intérieur d'une autre fonction,

> clusterExport(cl, c("opts", "timestep", "writeOutput", "mcWeights", "mcYears"))
([là](https://github.com/rte-antares-rpackage/antaresRead/blob/f183ffe1a27647e64c505fd7016e4e473eb47cbe/R/aggregateResult.R#L50))

ne nous permet pas d'avoir accès aux différentes variables dans le cluster dans la suite du code. J'obtiens l'erreur suivante:
```

 Error in get(name, envir = envir) : objet 'timestep' introuvable 
10. get(name, envir = envir) 
9. serialize(data, node$con) 
8. sendData.SOCKnode(con, list(type = type, data = value, tag = tag)) 
7. sendData(con, list(type = type, data = value, tag = tag)) 
6. postNode(con, "EXEC", list(fun = fun, args = args, return = return, 
    tag = tag)) 
5. sendCall(cl[[i]], fun, list(...)) 
4. clusterCall(cl, gets, name, get(name, envir = envir)) 
3. clusterExport(cl, c("opts", "timestep", "writeOutput", "mcWeights", 
    "mcYears")) at aggregateResult.R#50
2. parAggregateMCall(opts, nbcl = nbcl) at main.R#209
1. run_adq(opts, areas, virtual_areas, mcYears = "all", ext = "_adq", 
    nbcl = 10, antaresfbzone = "model_description_fb", showProgress = TRUE, 
    thresholdFilter = 1e+05) 
```

Je propose de transformer cette ligne en:

> clusterExport(cl, c("opts", "timestep", "writeOutput", "mcWeights", "mcYears"), envir = environment())

Ce qui permettrait de pouvoir faire fonctionner parAggregateMCall en parallèle à l'intérieur d'une autre fonction.

Bonne journée,

Hugo

**Comment by bthieurmel** [comment]
Thanks. Fix on master
