### ISSUE TITLE
Typo possible dans aggregateResult

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [rte-antares-rpackage/antaresRead#162]
Bonjour à vous,

J'ai remarqué un élément un peu bizarre dans aggregateResult.R:
```
struct <- list()
if(!is.null(dta$areas)){
  struct$areas <- dta$areas[,.SD, .SDcols = 1:SDcolsStartareas]
}

if(!is.null(dta$links)){
  struct$links <- dta$links[,.SD, .SDcols = 1:SDcolsStartareas]
}
if(!is.null(dta$clusters)){
  struct$clusters <- dta$clusters[,.SD, .SDcols = 1:SDcolsStartClust]
}

[...]

if(!is.null(struct$areas$day)){
  struct$areas$day <- ifelse(nchar(struct$areas$day) == 1,
                             paste0("0", struct$areas$day),
                             as.character(struct$areas$day))
}
if(!is.null(struct$links$day)){
  struct$links$day <- ifelse(nchar(struct$links$day) == 1,
                             paste0("0", struct$links$day),
                             as.character(struct$links$day))
}
if(!is.null(struct$links$day)){
  struct$clusters$day <- ifelse(nchar(struct$clusters$day) == 1,
                                paste0("0", struct$clusters$day),
                                as.character(struct$clusters$day))
}
```

([là](https://github.com/rte-antares-rpackage/antaresRead/blob/f183ffe1a27647e64c505fd7016e4e473eb47cbe/R/aggregateResult.R#L281))

La condition de cette dernière boucle if porte sur les links de la variable struct, alors qu'elle modifie les clusters de struct. Je ne connais pas bien le fonctionnement de cette fonction, mais ça me semble curieux étant donné la structure des deux boucles précédentes. Est-ce que c'est bien le comportement attendu de la fonction, ou Est-ce qu'il y a là une typo ?

Désolé si jamais c'est normal,

Hugo

**Comment by bthieurmel** [comment]
Merci Hugo. Cela a déjà été corrigé, mais effectivement, ce n'était pas normal !
