### ISSUE TITLE
parAggregateMCall possible memory leak

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [rte-antares-rpackage/antaresRead#168]
Hello,

When using the _parAggregateMCall_ function on large studies, the RAM usage goes up at every iteration until my R session just crashes. I didn't manage to figure out when it comes from. In order to fix it I had to add a garbage collection instruction at the end of the main loop, on line 62 of the _aggregateResult.R_ file:
```
pblapply(todo, function(X){
    d <- list(X[[1]][1])
    names(d) <- X[[1]][2]
    aggregateResult(opts, filtering = TRUE, verbose = 0, selected = d, 
                    timestep = timestep, writeOutput = writeOutput, mcWeights = mcWeights, mcYears = mcYears)
    # There was some kind of memory leak here, I don't really know why, but this gc() helped
    gc()
  }, cl = cl)
```
I don't know if this is an acceptable fix, but it seemed to do the trick.

**Comment by bthieurmel** [comment]
Thanks. Fix on github
