### ISSUE TITLE
aggregateResult improvement

### ISSUE THREAD

**Issue by hugo-antoine-rtei** [rte-antares-rpackage/antaresRead#170]
Hello,

I noticed a small thing that seemed odd in `R/aggregateResult.R` that you might want to take a look at. In Line 33, you reuse areas to fill in cluster: `custers <- areas`, this assumes that every areas contains clusters. I think that replacing this line with: `clusters <- getAreas(withClustersOnly = TRUE, opts = opts)` would be more appropriate, and would avoid some unintended behavior.

**Comment by bthieurmel** [comment]
Thanks. Fix on github.
