### ISSUE TITLE
Cannot read thermal availability with readInputTS()

### ISSUE THREAD

**Issue by fcattaneorte** [rte-antares-rpackage/antaresRead#43]
**I can load different inputs with readInputTS(), however I cannot do it for thermal availability.**

```
library(antaresRead)

path <-  "E:\\SEDRE\\Antares Rzo BP2014\\2020\\Zonal_2020_Declassement_nucleaire_2017\\Zonal_2020_Declassement_nuc_2017_2020"

setSimulationPath(path, "input")

areas <-  c("05_FR")

# Charger les LOAD fonctionne
load_z5 <- readInputTS(load = areas)

# Charger les ror fonctionnent
ror_z5 <- readInputTS(ror = areas)

# Charger la dispo thermique renvoie une erreur :
dispo_thermique_z5 <- readInputTS(thermalAvailabilities = areas, simplify = TRUE)


```

`Error in `[.data.table`(x, , `:=`(c(colsToAdd), newCols[x$timeId, colsToAdd,  : Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though.
`

**Comment by FrancoisGuillem** [comment]
Merci pour le retour. Je suis en train de regarder ça et effectivement, ça ne marche pas,

**Comment by FrancoisGuillem** [comment]
Par contre, moi j'ai un autre type d'erreur. Est-ce que tu pourrais me dire quelle version d'Antares tu utilises ? Les séries sont-elles bien présentes dans le dossier d'input (input/thermal/series/05_fr/nom_du_cluster/series.txt) ?

**Comment by jalazawa** [comment]
J'ai aussi testé avec ce code avec la nouvelle version  --> pas de pb , mais ...

```R
> library(antaresRead)
> path <-  "E:\\ANTARES\\Exemple_antares\\3_petit_exemple\\PackagesR\\test_case"
> setSimulationPath(path, "input")
Antares project 'Test_packages_R' (E:/ANTARES/Exemple_antares/3_petit_exemple/PackagesR/test_case)
Mode Input

Content:
 - Number of areas: 10
 - Number of districts: 2
 - Number of links: 12
Warning message:
Parameter 'horizon' is missing or inconsistent with 'january.1st' and 'leapyear'. Assume correct year is 2030.
To avoid this warning message in future simulations, open the study with Antares and go to the simulation tab, put a valid year number in the cell 'horizon' and use consistent values for parameters 'Leap year' and '1st january'. 
> areas <-  c("a")
> load_z5 <- readInputTS(load = areas)
Importing load
  |==========================================================================================| 100%
> ror_z5 <- readInputTS(ror = areas)
Importing ror
  |==========================================================================================| 100%
> dispo_thermique_z5 <- readInputTS(thermalAvailabilities = areas, simplify = TRUE)
Importing thermalAvailabilities
  |==========================================================================================| 100%
```

Est-ce que tu as encore le problème @fcattaneorte en installant la nouvelle version du package ? 

via install.packages("antaresRead")

sinon, je pense que c'est peut etre une histoire de typo : est-ce que le noeud ne s'appelle pas 05_fr au lieu de 05_FR ? 

Si le problème est résolu, est-ce qu'on peut clore le ticket @fcattaneorte ?

**Comment by fcattaneorte** [comment]
Effectivement il semble que c'était un problème de typo. Je ne l'ai pas détecté car l'import semblait fonctionner avec hydro et load bizarrement.

Merci et désolé de cette erreur. Vous pouvez fermer le ticket.

**Comment by jalazawa** [comment]
Merci pour le retour.
