### ISSUE TITLE
readInputTS error setcolorder....

### ISSUE THREAD

**Issue by payementcha** [rte-antares-rpackage/antaresRead#45]
Bonjour, 

J'ai eu ce message d'erreur pour la fonction readInputTS que je ne comprends pas ? 
J'ai pourtant déjà reussi à la faire fonctionner à un autre moment.

```
Importing thermalAvailabilities
  |                                                                                                |   0%
Error in setcolorder(res, c("area", "cluster", "timeId", setdiff(names(res),  : 
  neworder is length 3 but x has 2 columns.
```

Merci par avance, 

Charles

**Comment by FrancoisGuillem** [comment]
Ca vient potentiellement du fait que tous les clusters d'une zone ont été désactivés. Normalement ça devrait être corrigé dans la prochaine mise à jour. En attendant, ce que tu peux faire, c'est vérifier quels zones ont des clusters actifs et  n'importer les données de cluster que pour ces zones là.

**Comment by payementcha** [comment]
J'essaye d'importer le noeud donc tous les clusters ne sont pas inactifs seulement certains. 
Sur ces clusters inactifs par contre ANTARES ne génère pas de time series... c'est peut-être la cause du soucis ? 
Est-ce que je peux selectionner les clusters pour échapper à ce problème ? 

A+ et merci, 

Charles

**Comment by FrancoisGuillem** [comment]
Ah oui zut ! Cava pas marcher en fait. Je vais soumettre la mise à jour maintenant du coup et elle devrait être disponible dans quelques jours. Si c'est urgent je peux t'envoyer la nouvelle version par mail

**Comment by payementcha** [comment]
Salut, 

Si tu l'as déjà je veux bien ouais;.. j'ai des simus qui tourne et un peu de temps pour essayer de faire quelques analyses. 

A+ et merci,

Charles

**Comment by jalazawa** [comment]
Je viens de tester la commande suivante avec une étude dont tous les clusters ne sont pas actif. 

pas de pb. 

> myData<-readAntares(clusters = "all", thermalAvailabilities = TRUE, areas = "all")
