### ISSUE TITLE
Read values of optimization criterion (Antares>=6.0.2)

### ISSUE THREAD

**Issue by FrancoisGuillem** [rte-antares-rpackage/antaresRead#48]

**Comment by FrancoisGuillem** [comment]
@baptsegu, la fonction est prête, elle s'appelle `readOptimCriteria()`. Je pense qu'ill faudrait juste trouver des noms de colonne un peu plus explicites que "criterion1" et "criterion2"

**Comment by baptsegu** [comment]
Merci François,

Avec la v6 la fonction fonctionne au top !

Avec la v5 (quand l'option "export mps" est activé), la fonction retourne un tableau de `NA `en raison d'une syntaxe des fichiers de critère différente : 

**v5**
`* CoutOptimalDeLaSolution:   2.576705e+007`

**v6**
`* Optimal criterion value :   2.3468867037e+07`

Serait-il possible de gérer les deux formats ?

Les noms des colonnes sont très bien comme ça.

**Comment by FrancoisGuillem** [comment]
Comment vous allez faire maintenant si vous dépassez 9,999e+99 ? :p

**Comment by baptsegu** [comment]
ohhh... le jour où on aura autant de milliards d'euros on ne s'en souciera plus.
