### ISSUE TITLE
setSimulationPath() : adaptation to V6

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresRead#49]
Dear François,

Since ANTARES v6, a new directory, called "maps", is created by ANTARES in the output folder.
This directory include pictures of the ANTARES maps saved within the GUI.

Since this new folder is in the output directory, `setSimulationPath()` interprets it as a folder which includes outputs of a simulation.
It can produce some errors. Typically when using `setSimulationPath(studyPath, -1)`.

**Could it be possible to filter the "maps" directory in setSimulationPath() so as to ignore it  ?**

Thank you :)

Baptiste

**Comment by FrancoisGuillem** [comment]
Ca devrait être corrigé dans la dernière version de développement. Tu pourras  vérifier ?

**Comment by jalazawa** [comment]
des news @baptsegu ?

**Comment by baptsegu** [comment]
Ça marche !
