### ISSUE TITLE
test with all antares examples 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresRead#60]
Can we test some functions with all antares examples ? loop ?

**Comment by jalazawa** [comment]
Au lieu de pointer vers une étude particulière, pourrait-on envisager que certains tests soient réaliser pour une série d'études contenues dans un dossier ? en utilisant un sapply ? ou lapply ? 

On lancerait ces tests en local dans une session R en fond. 

Pour inclure le cas actuel dans la cible, on pourrait pointer vers le dossier temporaire crée et pas l'étude. 

Cela permettrait de couvrir plus de cas de tests tout en ne stockant pas dans le package N études. 

A discuter.

**Comment by TitouanRobert** [comment]
C'est déjà le fonctionnement de la plupart des tests, pour tester à la fois h5 et txt, Le fonctionnement : on donne au test une variable : studyPathS (contenant plusieurs path). Le test est ensuite lancé dans un sapply sur tous les studyPathS.
