### ISSUE TITLE
h5 : Taille readAntares VS readAntaresH5

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresRead#64]
Taille différentes entre readh5 et read. Voir si sur une grosse étude l'impact est important et regarder d’où cela peu venir.

**Comment by TitouanRobert** [comment]
Sur une grosse étude on a 3% de différence. Pour moi c'est pas problématique qu'en penses-tu?

**Comment by jalazawa** [comment]
OK
