### ISSUE TITLE
h5 : fonction : addStraitments : n'a pas l'air de fonctionner pour l'ajout de colonne

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresRead#65]
Pourrais-tu me ré-affecter le ticket une fois que la documentation sur l'argument select avec les alias Out_"traitement" a été réalisée ?

Pour l'instant, je n'ai que 18 alias.

**Comment by TitouanRobert** [comment]
Ajouté à la doc de la fonction addStraitments

**Comment by jalazawa** [comment]
OK
