### ISSUE TITLE
h5 : writeAntaresH5 : add tests --> goal 95% for this function 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresRead#72]
only tests to this file 

https://codecov.io/gh/rte-antares-rpackage/antaresRead/src/eb365002ad00960df89507da6ffaaf5686dbb63f/R/h5_writeH5ByYear.R

**Comment by jalazawa** [comment]
News about nbCores in Travis ?

**Comment by bthieurmel** [comment]
We have to test using trusty os, with 2 cores : 

````
sudo: required 
dist: trusty
````

**Comment by bthieurmel** [comment]
And add this ``Sys.unsetenv("R_TESTS")``

**Comment by bthieurmel** [comment]
Ok. See https://codecov.io/gh/rte-antares-rpackage/antaresRead/src/19c4ea35fba4e856c003e2e3f5f40f5ccb63bba2/R/h5_writeH5ByYear.R

and 19c4ea3

**Comment by jalazawa** [comment]
OK
