### ISSUE TITLE
h5 : writeAntaresH5 : proposition de simplification : allData 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresRead#81]
Je propose de rajouter un paramètre à cette fonction permettant d'écrire toutes les données et de ne rien oublier ! 

la ligne ci-dessous est trop longue. 

Je propose de rajouter un paramètre "allData" permettant l'écriture de toutes les données. 

paramètre à inclure dans allData 

- writeMcAll
- misc 
- thermalAvailabilities
- hydroStorage
- hydroStorageMaxPower
- reserve
- linkCapacity
- mustRun
- thermalModulation

```R 
writeAntaresH5(path = pathS2Out, misc = TRUE, thermalAvailabilities = TRUE,
               hydroStorage = TRUE, hydroStorageMaxPower = TRUE, reserve = TRUE,
               linkCapacity = TRUE, mustRun = TRUE, thermalModulation = TRUE,
               writeAllSimulations = TRUE, overwrite = TRUE)

```

**Comment by TitouanRobert** [comment]
Fait (commit sur antaresProcessing)

**Comment by jalazawa** [comment]
TODO   #83

**Comment by jalazawa** [comment]
OK
